---
# Ansible Playbook for Oracle Runtime Client (v12.2.0) installation
# -------------------------------------------------------------------
# License: MIT
# github.com/zicklam/ansible-oracle-client
#  
- name: Ansible Playbook for Oracle Runtime Client (v12.2.0) installation
  hosts: oracle
  tasks:
    - include: 'tasks/main.yml'
  vars_files:
    - 'defaults/main.yml'
    - 'vars/main.yml'
  environment:
    #http_proxy:  http://proxy:3128
    #https_proxy: http://proxy:3128
    #no_proxy:    localhost
